use_frameworks!
platform :ios, '10.0'

target 'ERPINCodeViewController_Example' do
  pod 'ERPINCodeViewController', :path => '../'

  target 'ERPINCodeViewController_Tests' do
    inherit! :search_paths

    
  end
end
